DROP TABLE IF EXISTS voter;
CREATE TABLE IF NOT EXISTS voter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  nim CHAR(10) UNIQUE NOT NULL,
  token CHAR(6) NOT NULL,
  has_voted BOOLEAN DEFAULT 0
);

DROP TABLE IF EXISTS sessions;
CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  nim CHAR(10) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS candidates;
CREATE TABLE IF NOT EXISTS candidates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  nim CHAR(10) UNIQUE NOT NULL,
  major TEXT NOT NULL,
  vision TEXT NOT NULL,
  mission TEXT NOT NULL,
  programme TEXT NOT NULL,
  photo_url TEXT
);